param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectDir
)

$ErrorActionPreference = 'Stop'
$publicUrl = 'https://irgri.uk'
$wsUrl = 'wss://irgri.uk'

$env:CROSSLINE_API_URL = $publicUrl
$env:CROSSLINE_WS_URL = $wsUrl

$configPath = [IO.Path]::Combine($ProjectDir, 'scripts', '.crossline-tunnel.env')
$configLines = @(
    '# Auto-generated by update-runtime-config.ps1',
    "CROSSLINE_API_URL=$publicUrl",
    "CROSSLINE_WS_URL=$wsUrl"
)

$encoding = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllLines($configPath, $configLines, $encoding)

$jsonConfig = [ordered]@{}
$jsonConfig['generatedAt'] = (Get-Date).ToUniversalTime().ToString('o')
$jsonConfig['apiOrigin'] = $publicUrl
$jsonConfig['wsOrigin'] = $wsUrl

$jsonConfigPath = [IO.Path]::Combine($ProjectDir, 'scripts', 'crossline-runtime-config.json')
$jsonContent = ($jsonConfig | ConvertTo-Json -Depth 2)
[IO.File]::WriteAllText($jsonConfigPath, $jsonContent, $encoding)

Write-Output "TUNNEL_URL=$publicUrl"
Write-Output "WS_URL=$wsUrl"
Write-Output "CONFIG_PATH=$configPath"
Write-Output "JSON_CONFIG_PATH=$jsonConfigPath"
